# Generated by Django 4.1.3 on 2023-10-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date_posted',
        ),
    ]
