# Generated by Django 4.2.16 on 2025-09-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
