# Generated by Django 4.2.16 on 2024-10-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0001_initial'),
        ('feed', '0002_remove_posts_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPage.profile'),
        ),
    ]
