# Generated by Django 4.2.16 on 2024-10-17 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
