# Generated by Django 4.2.16 on 2024-10-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_posts_comments_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='text',
        ),
    ]
